CREATE TABLE "EmergencyCase" ("id" TEXT NOT NULL,"patientId" TEXT NOT NULL,"hospitalId" TEXT NOT NULL,"doctorId" TEXT,"triageLevel" TEXT NOT NULL DEFAULT '3',"chiefComplaint" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'ARRIVED',"arrivalAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"disposition" TEXT,CONSTRAINT "EmergencyCase_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ICUStay" ("id" TEXT NOT NULL,"patientId" TEXT NOT NULL,"hospitalId" TEXT NOT NULL,"doctorId" TEXT,"bedLabel" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"acuity" TEXT NOT NULL DEFAULT 'CRITICAL',"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"endedAt" TIMESTAMP(3),CONSTRAINT "ICUStay_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OTCase" ("id" TEXT NOT NULL,"patientId" TEXT NOT NULL,"hospitalId" TEXT NOT NULL,"doctorId" TEXT,"procedure" TEXT NOT NULL,"scheduledAt" TIMESTAMP(3) NOT NULL,"status" TEXT NOT NULL DEFAULT 'SCHEDULED',"theatre" TEXT,CONSTRAINT "OTCase_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BloodUnit" ("id" TEXT NOT NULL,"hospitalId" TEXT NOT NULL,"bloodGroup" TEXT NOT NULL,"component" TEXT NOT NULL,"donationCode" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'AVAILABLE',"expiresAt" TIMESTAMP(3),CONSTRAINT "BloodUnit_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AmbulanceTrip" ("id" TEXT NOT NULL,"hospitalId" TEXT NOT NULL,"patientId" TEXT,"vehicleCode" TEXT NOT NULL,"driverName" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'AVAILABLE',"pickupLocation" TEXT,"destination" TEXT,"dispatchedAt" TIMESTAMP(3),"arrivedAt" TIMESTAMP(3),"completedAt" TIMESTAMP(3),CONSTRAINT "AmbulanceTrip_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "BloodUnit_donationCode_key" ON "BloodUnit"("donationCode");
CREATE INDEX "EmergencyCase_hospitalId_status_arrivalAt_idx" ON "EmergencyCase"("hospitalId","status","arrivalAt");
CREATE INDEX "EmergencyCase_patientId_arrivalAt_idx" ON "EmergencyCase"("patientId","arrivalAt");
CREATE INDEX "ICUStay_hospitalId_status_idx" ON "ICUStay"("hospitalId","status");
CREATE INDEX "ICUStay_patientId_startedAt_idx" ON "ICUStay"("patientId","startedAt");
CREATE INDEX "OTCase_hospitalId_status_scheduledAt_idx" ON "OTCase"("hospitalId","status","scheduledAt");
CREATE INDEX "BloodUnit_hospitalId_bloodGroup_status_idx" ON "BloodUnit"("hospitalId","bloodGroup","status");
CREATE INDEX "AmbulanceTrip_hospitalId_status_idx" ON "AmbulanceTrip"("hospitalId","status");
ALTER TABLE "EmergencyCase" ADD CONSTRAINT "EmergencyCase_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmergencyCase" ADD CONSTRAINT "EmergencyCase_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmergencyCase" ADD CONSTRAINT "EmergencyCase_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "Doctor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ICUStay" ADD CONSTRAINT "ICUStay_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ICUStay" ADD CONSTRAINT "ICUStay_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ICUStay" ADD CONSTRAINT "ICUStay_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "Doctor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "OTCase" ADD CONSTRAINT "OTCase_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OTCase" ADD CONSTRAINT "OTCase_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OTCase" ADD CONSTRAINT "OTCase_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "Doctor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "BloodUnit" ADD CONSTRAINT "BloodUnit_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AmbulanceTrip" ADD CONSTRAINT "AmbulanceTrip_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AmbulanceTrip" ADD CONSTRAINT "AmbulanceTrip_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE SET NULL ON UPDATE CASCADE;
