"use client";
import { useEffect, useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000";
type Patient={id:string;mrn:string;firstName:string;lastName:string}; type Invoice={id:string;status:string;total:string|number;patient:Patient;items:{description:string;quantity:number;unitPrice:string|number;total:string|number}[];payments:{amount:string|number;method:string;paidAt:string}[]};
export default function Billing(){const [patients,setPatients]=useState<Patient[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[patientId,setPatientId]=useState(""),[description,setDescription]=useState("Consultation"),[price,setPrice]=useState("500"),[message,setMessage]=useState("");
const load=()=>{fetch(`${API}/api/v1/patients`).then(r=>r.json()).then(x=>setPatients(x.data||[]));fetch(`${API}/api/v1/billing/invoices`).then(r=>r.json()).then(x=>setInvoices(x.data||[]))}; useEffect(load,[]);
async function createInvoice(){if(!patientId||!description||Number(price)<0)return;const r=await fetch(`${API}/api/v1/billing/invoices`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({patientId,items:[{description,quantity:1,unitPrice:Number(price)}]})});const x=await r.json();setMessage(r.ok?"Invoice created":x.error||"Could not create invoice");if(r.ok){setDescription("Consultation");setPrice("500");load()}}
async function pay(i:Invoice){const outstanding=Number(i.total)-i.payments.reduce((s,p)=>s+Number(p.amount),0);if(outstanding<=0)return;const r=await fetch(`${API}/api/v1/billing/invoices/${i.id}/payments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({amount:outstanding,method:"CASH"})});const x=await r.json();setMessage(r.ok?"Payment recorded":x.error||"Payment failed");if(r.ok)load()}
return <main><style>{`*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui;background:#f6f8fb;color:#172033}main{min-height:100vh;padding:32px;max-width:1400px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;gap:16px}.back{color:#4967d8;text-decoration:none}.grid{display:grid;grid-template-columns:360px 1fr;gap:20px;margin-top:24px}.card{background:white;border:1px solid #e5e9f0;border-radius:18px;padding:20px;box-shadow:0 8px 28px #1720330d}input,select,button{width:100%;padding:12px;border-radius:10px;border:1px solid #d9deea;margin:6px 0 12px;font:inherit}button{background:#172033;color:white;cursor:pointer}.row{display:flex;justify-content:space-between;gap:12px;padding:14px 0;border-bottom:1px solid #edf0f5}.pill{padding:5px 9px;border-radius:999px;background:#eef3ff;font-size:12px}.muted{color:#6c7585;font-size:13px}@media(max-width:800px){.grid{grid-template-columns:1fr}main{padding:18px}}`}</style><div className="top"><div><a className="back" href="/">← Command Center</a><h1>Billing & Revenue</h1><p className="muted">Invoices, payments and outstanding patient balances.</p></div><span className="pill">Operational billing</span></div><div className="grid"><section className="card"><h2>New invoice</h2><label>Patient<select value={patientId} onChange={e=>setPatientId(e.target.value)}><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.mrn} · {p.firstName} {p.lastName}</option>)}</select></label><label>Service<input value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Amount<input type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)}/></label><button onClick={createInvoice}>Create invoice</button>{message&&<p className="muted">{message}</p>}</section><section className="card"><h2>Invoices</h2>{!invoices.length?<p className="muted">No invoices yet.</p>:invoices.map(i=>{const paid=i.payments.reduce((s,p)=>s+Number(p.amount),0),out=Math.max(0,Number(i.total)-paid);return <div className="row" key={i.id}><div><b>{i.patient.firstName} {i.patient.lastName}</b><div className="muted">{i.patient.mrn} · {i.items.map(x=>x.description).join(", ")}</div></div><div style={{textAlign:"right"}}><b>₹{Number(i.total).toFixed(2)}</b><div className="muted">{i.status} · outstanding ₹{out.toFixed(2)}</div>{out>0&&<button style={{width:"auto",padding:"7px 10px"}} onClick={()=>pay(i)}>Pay balance</button>}</div></div>})}</section></div></main>}
