CREATE TYPE "BedStatus" AS ENUM ('AVAILABLE','RESERVED','OCCUPIED','CLEANING','OUT_OF_SERVICE');
CREATE TYPE "AppointmentStatus" AS ENUM ('SCHEDULED','CHECKED_IN','IN_CONSULTATION','COMPLETED','CANCELLED','NO_SHOW');
CREATE TYPE "EncounterStatus" AS ENUM ('OPEN','CLOSED');
CREATE TYPE "AdmissionStatus" AS ENUM ('ACTIVE','TRANSFERRED','DISCHARGED');
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE','INACTIVE','LOCKED');

CREATE TABLE "Hospital" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"code" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"CONSTRAINT_Hospital_pk" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Hospital_code_key" ON "Hospital"("code");
CREATE TABLE "Campus" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"hospitalId" TEXT NOT NULL,"CONSTRAINT_Campus_pk" PRIMARY KEY ("id"));
CREATE TABLE "Building" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"campusId" TEXT NOT NULL,"CONSTRAINT_Building_pk" PRIMARY KEY ("id"));
CREATE TABLE "Floor" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"buildingId" TEXT NOT NULL,"CONSTRAINT_Floor_pk" PRIMARY KEY ("id"));
CREATE TABLE "Ward" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"floorId" TEXT NOT NULL,"CONSTRAINT_Ward_pk" PRIMARY KEY ("id"));
CREATE TABLE "Room" ("id" TEXT NOT NULL,"number" TEXT NOT NULL,"name" TEXT,"hospitalId" TEXT NOT NULL,"campusId" TEXT NOT NULL,"buildingId" TEXT NOT NULL,"floorId" TEXT NOT NULL,"wardId" TEXT NOT NULL,"CONSTRAINT_Room_pk" PRIMARY KEY ("id"));
CREATE TABLE "Bed" ("id" TEXT NOT NULL,"number" TEXT NOT NULL,"status" "BedStatus" NOT NULL DEFAULT 'AVAILABLE',"wardId" TEXT NOT NULL,"roomId" TEXT,"CONSTRAINT_Bed_pk" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Room_wardId_number_key" ON "Room"("wardId","number");
CREATE UNIQUE INDEX "Bed_wardId_number_key" ON "Bed"("wardId","number");
CREATE INDEX "Bed_roomId_status_idx" ON "Bed"("roomId","status");
CREATE TABLE "Department" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"code" TEXT NOT NULL,"hospitalId" TEXT NOT NULL,"CONSTRAINT_Department_pk" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Department_hospitalId_code_key" ON "Department"("hospitalId","code");
CREATE TABLE "User" ("id" TEXT NOT NULL,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',"hospitalId" TEXT,"CONSTRAINT_User_pk" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "Role" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"CONSTRAINT_Role_pk" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Role_name_key" ON "Role"("name");
CREATE TABLE "Permission" ("id" TEXT NOT NULL,"key" TEXT NOT NULL,"CONSTRAINT_Permission_pk" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Permission_key_key" ON "Permission"("key");
CREATE TABLE "UserRole" ("userId" TEXT NOT NULL,"roleId" TEXT NOT NULL,"CONSTRAINT_UserRole_pk" PRIMARY KEY ("userId","roleId"));
CREATE TABLE "RolePermission" ("roleId" TEXT NOT NULL,"permissionId" TEXT NOT NULL,"CONSTRAINT_RolePermission_pk" PRIMARY KEY ("roleId","permissionId"));
CREATE TABLE "Patient" ("id" TEXT NOT NULL,"mrn" TEXT NOT NULL,"firstName" TEXT NOT NULL,"lastName" TEXT NOT NULL,"dateOfBirth" TIMESTAMP(3),"phone" TEXT,"email" TEXT,"hospitalId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"CONSTRAINT_Patient_pk" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Patient_mrn_key" ON "Patient"("mrn");
CREATE TABLE "Allergy" ("id" TEXT NOT NULL,"patientId" TEXT NOT NULL,"substance" TEXT NOT NULL,"reaction" TEXT,"CONSTRAINT_Allergy_pk" PRIMARY KEY ("id"));
CREATE TABLE "Doctor" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"departmentId" TEXT NOT NULL,"CONSTRAINT_Doctor_pk" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Doctor_userId_key" ON "Doctor"("userId");
CREATE TABLE "Appointment" ("id" TEXT NOT NULL,"patientId" TEXT NOT NULL,"doctorId" TEXT NOT NULL,"departmentId" TEXT NOT NULL,"status" "AppointmentStatus" NOT NULL DEFAULT 'SCHEDULED',"scheduledAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"CONSTRAINT_Appointment_pk" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Appointment_encounter_placeholder" ON "Appointment"("id");
CREATE INDEX "Appointment_departmentId_scheduledAt_idx" ON "Appointment"("departmentId","scheduledAt");
CREATE INDEX "Appointment_doctorId_scheduledAt_idx" ON "Appointment"("doctorId","scheduledAt");
CREATE TABLE "Encounter" ("id" TEXT NOT NULL,"patientId" TEXT NOT NULL,"doctorId" TEXT NOT NULL,"status" "EncounterStatus" NOT NULL DEFAULT 'OPEN',"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"closedAt" TIMESTAMP(3),"appointmentId" TEXT,"CONSTRAINT_Encounter_pk" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Encounter_appointmentId_key" ON "Encounter"("appointmentId");
CREATE TABLE "ClinicalNote" ("id" TEXT NOT NULL,"encounterId" TEXT NOT NULL,"authorId" TEXT NOT NULL,"body" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"CONSTRAINT_ClinicalNote_pk" PRIMARY KEY ("id"));
CREATE TABLE "Diagnosis" ("id" TEXT NOT NULL,"encounterId" TEXT NOT NULL,"code" TEXT NOT NULL,"description" TEXT NOT NULL,"CONSTRAINT_Diagnosis_pk" PRIMARY KEY ("id"));
CREATE TABLE "ClinicalOrder" ("id" TEXT NOT NULL,"encounterId" TEXT NOT NULL,"type" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'ORDERED',"details" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"CONSTRAINT_ClinicalOrder_pk" PRIMARY KEY ("id"));
CREATE TABLE "Admission" ("id" TEXT NOT NULL,"patientId" TEXT NOT NULL,"bedId" TEXT NOT NULL,"status" "AdmissionStatus" NOT NULL DEFAULT 'ACTIVE',"admittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"dischargedAt" TIMESTAMP(3),"CONSTRAINT_Admission_pk" PRIMARY KEY ("id"));
CREATE INDEX "Admission_bedId_status_idx" ON "Admission"("bedId","status");
CREATE TABLE "AdmissionTransfer" ("id" TEXT NOT NULL,"admissionId" TEXT NOT NULL,"fromBedId" TEXT,"toBedId" TEXT,"transferredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"CONSTRAINT_AdmissionTransfer_pk" PRIMARY KEY ("id"));
CREATE TABLE "Vital" ("id" TEXT NOT NULL,"patientId" TEXT NOT NULL,"recordedBy" TEXT NOT NULL,"recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"temperature" DECIMAL(65,30),"heartRate" INTEGER,"respiratoryRate" INTEGER,"systolic" INTEGER,"diastolic" INTEGER,"spo2" DECIMAL(65,30),"CONSTRAINT_Vital_pk" PRIMARY KEY ("id"));
CREATE INDEX "Vital_patientId_recordedAt_idx" ON "Vital"("patientId","recordedAt");
CREATE TABLE "Prescription" ("id" TEXT NOT NULL,"patientId" TEXT NOT NULL,"doctorId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"CONSTRAINT_Prescription_pk" PRIMARY KEY ("id"));
CREATE TABLE "Invoice" ("id" TEXT NOT NULL,"patientId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'OPEN',"total" DECIMAL(65,30) NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"CONSTRAINT_Invoice_pk" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL,"userId" TEXT,"action" TEXT NOT NULL,"entity" TEXT NOT NULL,"entityId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"CONSTRAINT_AuditLog_pk" PRIMARY KEY ("id"));
CREATE INDEX "AuditLog_entity_entityId_idx" ON "AuditLog"("entity","entityId");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

ALTER TABLE "Campus" ADD CONSTRAINT "Campus_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Building" ADD CONSTRAINT "Building_campusId_fkey" FOREIGN KEY ("campusId") REFERENCES "Campus"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Floor" ADD CONSTRAINT "Floor_buildingId_fkey" FOREIGN KEY ("buildingId") REFERENCES "Building"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Ward" ADD CONSTRAINT "Ward_floorId_fkey" FOREIGN KEY ("floorId") REFERENCES "Floor"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Room" ADD CONSTRAINT "Room_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Room" ADD CONSTRAINT "Room_campusId_fkey" FOREIGN KEY ("campusId") REFERENCES "Campus"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Room" ADD CONSTRAINT "Room_buildingId_fkey" FOREIGN KEY ("buildingId") REFERENCES "Building"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Room" ADD CONSTRAINT "Room_floorId_fkey" FOREIGN KEY ("floorId") REFERENCES "Floor"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Room" ADD CONSTRAINT "Room_wardId_fkey" FOREIGN KEY ("wardId") REFERENCES "Ward"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Bed" ADD CONSTRAINT "Bed_wardId_fkey" FOREIGN KEY ("wardId") REFERENCES "Ward"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Bed" ADD CONSTRAINT "Bed_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "Room"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Department" ADD CONSTRAINT "Department_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "User" ADD CONSTRAINT "User_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "UserRole" ADD CONSTRAINT "UserRole_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserRole" ADD CONSTRAINT "UserRole_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RolePermission" ADD CONSTRAINT "RolePermission_permissionId_fkey" FOREIGN KEY ("permissionId") REFERENCES "Permission"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Patient" ADD CONSTRAINT "Patient_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Allergy" ADD CONSTRAINT "Allergy_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Doctor" ADD CONSTRAINT "Doctor_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Doctor" ADD CONSTRAINT "Doctor_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "Doctor"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Encounter" ADD CONSTRAINT "Encounter_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Encounter" ADD CONSTRAINT "Encounter_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "Doctor"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Encounter" ADD CONSTRAINT "Encounter_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ClinicalNote" ADD CONSTRAINT "ClinicalNote_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Diagnosis" ADD CONSTRAINT "Diagnosis_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ClinicalOrder" ADD CONSTRAINT "ClinicalOrder_encounterId_fkey" FOREIGN KEY ("encounterId") REFERENCES "Encounter"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Admission" ADD CONSTRAINT "Admission_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Admission" ADD CONSTRAINT "Admission_bedId_fkey" FOREIGN KEY ("bedId") REFERENCES "Bed"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AdmissionTransfer" ADD CONSTRAINT "AdmissionTransfer_admissionId_fkey" FOREIGN KEY ("admissionId") REFERENCES "Admission"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Vital" ADD CONSTRAINT "Vital_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Prescription" ADD CONSTRAINT "Prescription_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

INSERT INTO "Hospital" ("id","name","code","updatedAt") VALUES ('seed-hospital-main','SpecialCare Medical Center','SCMC',CURRENT_TIMESTAMP) ON CONFLICT ("code") DO NOTHING;
