import type { FastifyInstance } from "fastify";
import type { PrismaClient } from "@prisma/client";

const required = (v: unknown) => typeof v === "string" && v.trim().length > 0;

export async function registerDiagnosticsPharmacyRoutes(app: FastifyInstance, prisma: PrismaClient) {
  app.get("/api/v1/doctors", async () => ({ data: await prisma.doctor.findMany({ include: { user: { select: { id: true, email: true, status: true } }, department: true }, orderBy: { user: { email: "asc" } } }) }));
  app.get("/api/v1/diagnostics/orders", async (request) => { const q = request.query as { status?: string; type?: string; patientId?: string }; const type = q.type?.trim().toUpperCase(); const data = await prisma.clinicalOrder.findMany({ where: { ...(q.status ? { status: q.status.trim().toUpperCase() } : {}), ...(type ? { type } : { type: { in: ["LAB", "RADIOLOGY"] } }), ...(q.patientId ? { encounter: { patientId: q.patientId } } : {}) }, include: { encounter: { include: { patient: true, doctor: { include: { department: true } } } }, diagnosticResults: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { createdAt: "desc" }, take: 200 }); return { data }; });
  app.post("/api/v1/diagnostics/orders", async (request, reply) => { const b = request.body as { encounterId?: string; type?: string; details?: unknown }; const type = b.type?.trim().toUpperCase(); if (!required(b.encounterId) || !required(type)) return reply.code(400).send({ error: "encounterId and type are required" }); if (!["LAB", "RADIOLOGY"].includes(type!)) return reply.code(400).send({ error: "type must be LAB or RADIOLOGY" }); const encounter = await prisma.encounter.findUnique({ where: { id: b.encounterId } }); if (!encounter) return reply.code(404).send({ error: "Encounter not found" }); return reply.code(201).send(await prisma.clinicalOrder.create({ data: { encounterId: b.encounterId!, type: type!, details: b.details === undefined ? undefined : b.details as any } })); });
  app.post("/api/v1/diagnostics/orders/:id/results", async (request, reply) => { const { id } = request.params as { id: string }; const b = request.body as { status?: string; result?: unknown; reportedBy?: string }; if (!required(b.status) || b.result === undefined) return reply.code(400).send({ error: "status and result are required" }); const order = await prisma.clinicalOrder.findUnique({ where: { id }, include: { encounter: true } }); if (!order || !["LAB", "RADIOLOGY"].includes(order.type)) return reply.code(404).send({ error: "Diagnostic order not found" }); const result = await prisma.diagnosticResult.create({ data: { orderId: id, patientId: order.encounter.patientId, kind: order.type, status: b.status!.trim().toUpperCase(), result: b.result as any, reportedBy: b.reportedBy?.trim() || undefined, reportedAt: new Date() } }); await prisma.clinicalOrder.update({ where: { id }, data: { status: "RESULTED" } }); return reply.code(201).send(result); });
  app.get("/api/v1/patients/:id/diagnostics", async (request) => { const { id } = request.params as { id: string }; return { data: await prisma.diagnosticResult.findMany({ where: { patientId: id }, include: { order: true }, orderBy: { createdAt: "desc" }, take: 100 }) }; });
  app.post("/api/v1/prescriptions", async (request, reply) => { const b = request.body as { patientId?: string; doctorId?: string; items?: Array<{ medication?: string; dose?: string; route?: string; frequency?: string; duration?: string; quantity?: number }> }; if (!required(b.patientId) || !required(b.doctorId) || !Array.isArray(b.items) || !b.items.length) return reply.code(400).send({ error: "patientId, doctorId and at least one medication item are required" }); if (b.items.some(i => !required(i.medication) || (i.quantity !== undefined && (!Number.isInteger(i.quantity) || i.quantity < 1)))) return reply.code(400).send({ error: "Each medication requires a name and valid quantity" }); const patient = await prisma.patient.findUnique({ where: { id: b.patientId } }); const doctor = await prisma.doctor.findUnique({ where: { id: b.doctorId } }); if (!patient) return reply.code(404).send({ error: "Patient not found" }); if (!doctor) return reply.code(404).send({ error: "Doctor not found" }); return reply.code(201).send(await prisma.prescription.create({ data: { patientId: b.patientId!, doctorId: b.doctorId!, items: { create: b.items.map(i => ({ medication: i.medication!.trim(), dose: i.dose?.trim(), route: i.route?.trim(), frequency: i.frequency?.trim(), duration: i.duration?.trim(), quantity: i.quantity })) } }, include: { doctor: { include: { department: true } }, items: true } })); });
  app.get("/api/v1/prescriptions", async (request) => { const q = request.query as { patientId?: string; status?: string }; return { data: await prisma.prescription.findMany({ where: { ...(q.patientId ? { patientId: q.patientId } : {}), ...(q.status ? { status: q.status.trim().toUpperCase() } : {}) }, include: { doctor: { include: { department: true } }, patient: true, items: { include: { administrations: { orderBy: { administeredAt: "desc" }, take: 5 } } } }, orderBy: { createdAt: "desc" }, take: 100 }) }; });
  app.post("/api/v1/prescription-items/:id/administrations", async (request, reply) => { const { id } = request.params as { id: string }; const b = request.body as { administeredBy?: string; status?: string; notes?: string }; if (!required(b.administeredBy)) return reply.code(400).send({ error: "administeredBy is required" }); const item = await prisma.prescriptionItem.findUnique({ where: { id }, include: { prescription: true } }); if (!item) return reply.code(404).send({ error: "Prescription item not found" }); return reply.code(201).send(await prisma.medicationAdministration.create({ data: { prescriptionItemId: id, patientId: item.prescription.patientId, administeredBy: b.administeredBy!, status: b.status?.trim().toUpperCase() || "GIVEN", notes: b.notes?.trim() || undefined } })); });
  app.get("/api/v1/patients/:id/medications", async (request) => { const { id } = request.params as { id: string }; return { data: await prisma.prescription.findMany({ where: { patientId: id }, include: { doctor: { include: { department: true } }, items: { include: { administrations: { orderBy: { administeredAt: "desc" }, take: 10 } } } }, orderBy: { createdAt: "desc" } }) }; });
  app.get("/api/v1/billing/invoices", async (request) => { const q = request.query as { patientId?: string; status?: string }; return { data: await prisma.invoice.findMany({ where: { ...(q.patientId ? { patientId: q.patientId } : {}), ...(q.status ? { status: q.status.trim().toUpperCase() } : {}) }, include: { patient: true, items: true, payments: { orderBy: { paidAt: "desc" } } }, orderBy: { createdAt: "desc" }, take: 200 }) }; });
  app.post("/api/v1/billing/invoices", async (request, reply) => { const b = request.body as { patientId?: string; items?: Array<{ description?: string; quantity?: number; unitPrice?: number }> }; if (!required(b.patientId) || !Array.isArray(b.items) || !b.items.length) return reply.code(400).send({ error: "patientId and at least one invoice item are required" }); if (b.items.some(i => !required(i.description) || !Number.isInteger(i.quantity ?? 1) || (i.quantity ?? 1) < 1 || typeof i.unitPrice !== "number" || !Number.isFinite(i.unitPrice) || i.unitPrice < 0)) return reply.code(400).send({ error: "Each invoice item needs a valid description, quantity and non-negative price" }); const patient = await prisma.patient.findUnique({ where: { id: b.patientId } }); if (!patient) return reply.code(404).send({ error: "Patient not found" }); const items = b.items.map(i => { const quantity = i.quantity ?? 1; const unitPrice = i.unitPrice!; return { description: i.description!.trim(), quantity, unitPrice, total: quantity * unitPrice }; }); const total = items.reduce((sum, i) => sum + i.total, 0); return reply.code(201).send(await prisma.invoice.create({ data: { patientId: b.patientId!, total, items: { create: items } }, include: { patient: true, items: true } })); });
  app.post("/api/v1/billing/invoices/:id/payments", async (request, reply) => { const { id } = request.params as { id: string }; const b = request.body as { amount?: number; method?: string; reference?: string }; if (typeof b.amount !== "number" || !Number.isFinite(b.amount) || b.amount <= 0 || !required(b.method)) return reply.code(400).send({ error: "positive amount and payment method are required" }); const invoice = await prisma.invoice.findUnique({ where: { id }, include: { payments: true } }); if (!invoice) return reply.code(404).send({ error: "Invoice not found" }); const paid = invoice.payments.filter(p => p.status === "COMPLETED").reduce((s,p) => s + Number(p.amount), 0); const remaining = Number(invoice.total) - paid; if (b.amount > remaining + 0.0001) return reply.code(409).send({ error: "Payment exceeds outstanding balance" }); const payment = await prisma.payment.create({ data: { invoiceId: id, amount: b.amount, method: b.method.trim().toUpperCase(), reference: b.reference?.trim() || undefined } }); if (paid + b.amount + 0.0001 >= Number(invoice.total)) await prisma.invoice.update({ where: { id }, data: { status: "PAID" } }); return reply.code(201).send(payment); });
  app.get("/api/v1/billing/summary", async () => { const invoices = await prisma.invoice.findMany({ include: { payments: true } }); const billed = invoices.reduce((s,i) => s + Number(i.total), 0); const paid = invoices.reduce((s,i) => s + i.payments.filter(p => p.status === "COMPLETED").reduce((x,p) => x + Number(p.amount), 0), 0); return { invoices: invoices.length, billed, paid, outstanding: Math.max(0, billed - paid) }; });
  app.get("/api/v1/inventory/items", async (request) => { const q = request.query as { search?: string; lowStock?: string }; const search = q.search?.trim(); let data = await prisma.inventoryItem.findMany({ where: { active: true, ...(search ? { OR: [{ name: { contains: search, mode: "insensitive" } }, { sku: { contains: search, mode: "insensitive" } }] } : {}) }, orderBy: { name: "asc" }, take: 500 }); if (q.lowStock === "true") data = data.filter(i => i.quantity <= i.reorderLevel); return { data }; });
  app.post("/api/v1/inventory/items", async (request, reply) => { const b = request.body as { sku?: string; name?: string; category?: string; unit?: string; quantity?: number; reorderLevel?: number }; if (!required(b.sku) || !required(b.name) || !Number.isInteger(b.quantity ?? 0) || (b.quantity ?? 0) < 0 || !Number.isInteger(b.reorderLevel ?? 0) || (b.reorderLevel ?? 0) < 0) return reply.code(400).send({ error: "sku, name and valid non-negative quantities are required" }); try { return reply.code(201).send(await prisma.inventoryItem.create({ data: { sku: b.sku!.trim().toUpperCase(), name: b.name!.trim(), category: b.category?.trim() || undefined, unit: b.unit?.trim() || "unit", quantity: b.quantity ?? 0, reorderLevel: b.reorderLevel ?? 0 } })); } catch { return reply.code(409).send({ error: "SKU already exists" }); } });
  app.post("/api/v1/inventory/items/:id/movements", async (request, reply) => { const { id } = request.params as { id: string }; const b = request.body as { type?: string; quantity?: number; reason?: string; reference?: string }; const type = b.type?.trim().toUpperCase(); if (!["RECEIPT", "ISSUE", "ADJUSTMENT"].includes(type || "") || !Number.isInteger(b.quantity) || !b.quantity || b.quantity < 1) return reply.code(400).send({ error: "type and positive integer quantity are required" }); const item = await prisma.inventoryItem.findUnique({ where: { id } }); if (!item) return reply.code(404).send({ error: "Inventory item not found" }); if (type === "ISSUE" && item.quantity < b.quantity!) return reply.code(409).send({ error: "Insufficient stock" }); const delta = type === "ISSUE" ? -b.quantity! : b.quantity!; return reply.code(201).send(await prisma.$transaction(async tx => { const movement = await tx.stockMovement.create({ data: { itemId: id, type: type!, quantity: b.quantity!, reason: b.reason?.trim(), reference: b.reference?.trim() } }); const updated = await tx.inventoryItem.update({ where: { id }, data: { quantity: { increment: delta } } }); return { movement, item: updated }; })); });
  app.get("/api/v1/inventory/items/:id/movements", async (request) => { const { id } = request.params as { id: string }; return { data: await prisma.stockMovement.findMany({ where: { itemId: id }, orderBy: { createdAt: "desc" }, take: 200 }) }; });
}
