import type { FastifyInstance } from "fastify";
import type { PrismaClient } from "@prisma/client";
const text=(v:unknown)=>typeof v==="string"&&v.trim().length>0;
export async function registerHospitalOperationsRoutes(app:FastifyInstance,prisma:PrismaClient){
 app.get("/api/v1/operations/summary",async()=>{const [emergency,icu,ot,blood,ambulance]=await Promise.all([prisma.emergencyCase.count({where:{status:{notIn:["DISCHARGED","CLOSED"]}}}),prisma.iCUStay.count({where:{status:"ACTIVE"}}),prisma.oTCase.count({where:{status:{in:["SCHEDULED","IN_PROGRESS"]}}}),prisma.bloodUnit.count({where:{status:"AVAILABLE"}}),prisma.ambulanceTrip.count({where:{status:"AVAILABLE"}})]);return{emergency,icu,ot,bloodAvailable:blood,ambulancesAvailable:ambulance}});
 app.get("/api/v1/emergency",async()=>({data:await prisma.emergencyCase.findMany({include:{patient:true,doctor:{include:{department:true}}},orderBy:{arrivalAt:"desc"},take:200})}));
 app.post("/api/v1/emergency",async(request,reply)=>{const b=request.body as {patientId?:string;hospitalId?:string;doctorId?:string;triageLevel?:string;chiefComplaint?:string};if(!text(b.patientId)||!text(b.hospitalId)||!text(b.chiefComplaint))return reply.code(400).send({error:"patientId, hospitalId and chiefComplaint are required"});const patient=await prisma.patient.findUnique({where:{id:b.patientId}});const hospital=await prisma.hospital.findUnique({where:{id:b.hospitalId}});if(!patient)return reply.code(404).send({error:"Patient not found"});if(!hospital)return reply.code(404).send({error:"Hospital not found"});return reply.code(201).send(await prisma.emergencyCase.create({data:{patientId:b.patientId!,hospitalId:b.hospitalId!,doctorId:b.doctorId||undefined,triageLevel:b.triageLevel?.trim()||"3",chiefComplaint:b.chiefComplaint!.trim()}}));});
 app.patch("/api/v1/emergency/:id",async(request,reply)=>{const {id}=request.params as {id:string};const b=request.body as {status?:string;triageLevel?:string;disposition?:string;doctorId?:string};const x=await prisma.emergencyCase.findUnique({where:{id}});if(!x)return reply.code(404).send({error:"Emergency case not found"});return prisma.emergencyCase.update({where:{id},data:{status:b.status?.trim().toUpperCase(),triageLevel:b.triageLevel?.trim(),disposition:b.disposition?.trim()||undefined,doctorId:b.doctorId||undefined}})});
 app.get("/api/v1/icu",async()=>({data:await prisma.iCUStay.findMany({include:{patient:true,doctor:{include:{department:true}}},orderBy:{startedAt:"desc"},take:200})}));
 app.post("/api/v1/icu",async(request,reply)=>{const b=request.body as {patientId?:string;hospitalId?:string;doctorId?:string;bedLabel?:string;acuity?:string};if(!text(b.patientId)||!text(b.hospitalId)||!text(b.bedLabel))return reply.code(400).send({error:"patientId, hospitalId and bedLabel are required"});const p=await prisma.patient.findUnique({where:{id:b.patientId}});if(!p)return reply.code(404).send({error:"Patient not found"});return reply.code(201).send(await prisma.iCUStay.create({data:{patientId:b.patientId!,hospitalId:b.hospitalId!,doctorId:b.doctorId||undefined,bedLabel:b.bedLabel!.trim(),acuity:b.acuity?.trim().toUpperCase()||"CRITICAL"}}));});
 app.patch("/api/v1/icu/:id/close",async(request,reply)=>{const {id}=request.params as {id:string};const x=await prisma.iCUStay.findUnique({where:{id}});if(!x)return reply.code(404).send({error:"ICU stay not found"});return prisma.iCUStay.update({where:{id},data:{status:"CLOSED",endedAt:new Date()}})});
 app.get("/api/v1/ot",async()=>({data:await prisma.oTCase.findMany({include:{patient:true,doctor:{include:{department:true}}},orderBy:{scheduledAt:"asc"},take:200})}));
 app.post("/api/v1/ot",async(request,reply)=>{const b=request.body as {patientId?:string;hospitalId?:string;doctorId?:string;procedure?:string;scheduledAt?:string;theatre?:string};if(!text(b.patientId)||!text(b.hospitalId)||!text(b.procedure)||!text(b.scheduledAt))return reply.code(400).send({error:"patientId, hospitalId, procedure and scheduledAt are required"});const when=new Date(b.scheduledAt!);if(Number.isNaN(when.getTime()))return reply.code(400).send({error:"Invalid scheduledAt"});const p=await prisma.patient.findUnique({where:{id:b.patientId}});if(!p)return reply.code(404).send({error:"Patient not found"});return reply.code(201).send(await prisma.oTCase.create({data:{patientId:b.patientId!,hospitalId:b.hospitalId!,doctorId:b.doctorId||undefined,procedure:b.procedure!.trim(),scheduledAt:when,theatre:b.theatre?.trim()||undefined}}));});
 app.patch("/api/v1/ot/:id",async(request,reply)=>{const {id}=request.params as {id:string};const b=request.body as {status?:string;theatre?:string};const x=await prisma.oTCase.findUnique({where:{id}});if(!x)return reply.code(404).send({error:"OT case not found"});return prisma.oTCase.update({where:{id},data:{status:b.status?.trim().toUpperCase(),theatre:b.theatre?.trim()||undefined}})});
 app.get("/api/v1/blood-bank",async()=>({data:await prisma.bloodUnit.findMany({orderBy:{expiresAt:"asc"},take:500})}));
 app.post("/api/v1/blood-bank",async(request,reply)=>{const b=request.body as {hospitalId?:string;bloodGroup?:string;component?:string;donationCode?:string;expiresAt?:string};if(!text(b.hospitalId)||!text(b.bloodGroup)||!text(b.component)||!text(b.donationCode))return reply.code(400).send({error:"hospitalId, bloodGroup, component and donationCode are required"});try{return reply.code(201).send(await prisma.bloodUnit.create({data:{hospitalId:b.hospitalId!,bloodGroup:b.bloodGroup!.trim().toUpperCase(),component:b.component!.trim().toUpperCase(),donationCode:b.donationCode!.trim().toUpperCase(),expiresAt:b.expiresAt?new Date(b.expiresAt):undefined}}))}catch{return reply.code(409).send({error:"Donation code already exists"})}});
 app.patch("/api/v1/blood-bank/:id",async(request,reply)=>{const {id}=request.params as {id:string};const b=request.body as {status?:string};const x=await prisma.bloodUnit.findUnique({where:{id}});if(!x)return reply.code(404).send({error:"Blood unit not found"});return prisma.bloodUnit.update({where:{id},data:{status:b.status?.trim().toUpperCase()}})});
 app.get("/api/v1/ambulances",async()=>({data:await prisma.ambulanceTrip.findMany({include:{patient:true},orderBy:{dispatchedAt:"desc"},take:200})}));
 app.post("/api/v1/ambulances",async(request,reply)=>{const b=request.body as {hospitalId?:string;patientId?:string;vehicleCode?:string;driverName?:string;pickupLocation?:string;destination?:string};if(!text(b.hospitalId)||!text(b.vehicleCode)||!text(b.driverName))return reply.code(400).send({error:"hospitalId, vehicleCode and driverName are required"});return reply.code(201).send(await prisma.ambulanceTrip.create({data:{hospitalId:b.hospitalId!,patientId:b.patientId||undefined,vehicleCode:b.vehicleCode!.trim().toUpperCase(),driverName:b.driverName!.trim(),pickupLocation:b.pickupLocation?.trim(),destination:b.destination?.trim(),status:"DISPATCHED",dispatchedAt:new Date()}}));});
 app.patch("/api/v1/ambulances/:id",async(request,reply)=>{const {id}=request.params as {id:string};const b=request.body as {status?:string};const x=await prisma.ambulanceTrip.findUnique({where:{id}});if(!x)return reply.code(404).send({error:"Ambulance trip not found"});const status=b.status?.trim().toUpperCase();const data:any={status};if(status==="ARRIVED")data.arrivedAt=new Date();if(status==="COMPLETED"){data.completedAt=new Date()}return prisma.ambulanceTrip.update({where:{id},data})});
}
