import Fastify from "fastify";
import cors from "@fastify/cors";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const app = Fastify({ logger: true });
await app.register(cors, { origin: true });

async function hospitalIdFor(input?: string) {
  if (input) return input;
  const existing = await prisma.hospital.findFirst({ orderBy: { createdAt: "asc" } });
  if (existing) return existing.id;
  const hospital = await prisma.hospital.create({ data: { name: "SpecialCare Medical Center", code: "SCMC" } });
  return hospital.id;
}
function mrn() { return `SC-${Date.now()}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`; }
const required = (value: unknown) => typeof value === "string" && value.trim().length > 0;

app.get("/health", async () => ({ status: "ok", service: "SpecialCare Hospital API", version: "0.6.0" }));
app.get("/api/v1/hospitals", async () => ({ data: await prisma.hospital.findMany({ include: { campuses: { include: { buildings: { include: { floors: { include: { wards: true } } } } } } }, orderBy: { createdAt: "asc" } }) }));
app.post("/api/v1/hospitals", async (request, reply) => { const b = request.body as { name?: string; code?: string }; if (!required(b.name) || !required(b.code)) return reply.code(400).send({ error: "name and code are required" }); try { return reply.code(201).send(await prisma.hospital.create({ data: { name: b.name!.trim(), code: b.code!.trim().toUpperCase() } })); } catch { return reply.code(409).send({ error: "Hospital code already exists" }); } });
app.post("/api/v1/campuses", async (request, reply) => { const b = request.body as { name?: string; hospitalId?: string }; if (!required(b.name) || !required(b.hospitalId)) return reply.code(400).send({ error: "name and hospitalId are required" }); return reply.code(201).send(await prisma.campus.create({ data: { name: b.name!.trim(), hospitalId: b.hospitalId! } })); });
app.post("/api/v1/buildings", async (request, reply) => { const b = request.body as { name?: string; campusId?: string }; if (!required(b.name) || !required(b.campusId)) return reply.code(400).send({ error: "name and campusId are required" }); return reply.code(201).send(await prisma.building.create({ data: { name: b.name!.trim(), campusId: b.campusId! } })); });
app.post("/api/v1/floors", async (request, reply) => { const b = request.body as { name?: string; buildingId?: string }; if (!required(b.name) || !required(b.buildingId)) return reply.code(400).send({ error: "name and buildingId are required" }); return reply.code(201).send(await prisma.floor.create({ data: { name: b.name!.trim(), buildingId: b.buildingId! } })); });
app.post("/api/v1/wards", async (request, reply) => { const b = request.body as { name?: string; floorId?: string }; if (!required(b.name) || !required(b.floorId)) return reply.code(400).send({ error: "name and floorId are required" }); return reply.code(201).send(await prisma.ward.create({ data: { name: b.name!.trim(), floorId: b.floorId! } })); });
app.post("/api/v1/rooms", async (request, reply) => { const b = request.body as { number?: string; name?: string; hospitalId?: string; campusId?: string; buildingId?: string; floorId?: string; wardId?: string }; if (![b.number,b.hospitalId,b.campusId,b.buildingId,b.floorId,b.wardId].every(required)) return reply.code(400).send({ error: "number and all hierarchy IDs are required" }); try { return reply.code(201).send(await prisma.room.create({ data: { number: b.number!.trim(), name: b.name?.trim() || undefined, hospitalId: b.hospitalId!, campusId: b.campusId!, buildingId: b.buildingId!, floorId: b.floorId!, wardId: b.wardId! } })); } catch { return reply.code(409).send({ error: "Room number already exists in this ward" }); } });
app.post("/api/v1/beds", async (request, reply) => { const b = request.body as { number?: string; wardId?: string; roomId?: string }; if (!required(b.number) || !required(b.wardId)) return reply.code(400).send({ error: "number and wardId are required" }); try { return reply.code(201).send(await prisma.bed.create({ data: { number: b.number!.trim(), wardId: b.wardId!, roomId: b.roomId || undefined }, include: { ward: true, room: true } })); } catch { return reply.code(409).send({ error: "Bed number already exists in this ward" }); } });
app.patch("/api/v1/beds/:id", async (request, reply) => { const { id } = request.params as { id: string }; const b = request.body as { status?: string; roomId?: string | null }; if (!b.status && b.roomId === undefined) return reply.code(400).send({ error: "status or roomId is required" }); try { return await prisma.bed.update({ where: { id }, data: { ...(b.status ? { status: b.status as any } : {}), ...(b.roomId !== undefined ? { roomId: b.roomId } : {}) }, include: { ward: true, room: true } }); } catch { return reply.code(404).send({ error: "Bed not found" }); } });
app.get("/api/v1/hierarchy", async (request, reply) => { const q = request.query as { hospitalId?: string }; const hospitals = await prisma.hospital.findMany({ where: q.hospitalId ? { id: q.hospitalId } : undefined, include: { campuses: { include: { buildings: { include: { floors: { include: { wards: { include: { rooms: { include: { beds: true }, orderBy: { number: "asc" } }, beds: { where: { roomId: null }, orderBy: { number: "asc" } } }, orderBy: { name: "asc" } } }, orderBy: { name: "asc" } } }, orderBy: { name: "asc" } } }, orderBy: { name: "asc" } } }); if (!hospitals.length) return reply.code(404).send({ error: "Hospital not found" }); return hospitals[0]; });

app.get("/api/v1/dashboard/summary", async () => ({ beds: { total: await prisma.bed.count(), occupied: await prisma.bed.count({ where: { status: "OCCUPIED" } }), available: await prisma.bed.count({ where: { status: "AVAILABLE" } }), cleaning: await prisma.bed.count({ where: { status: "CLEANING" } }) }, patients: { total: await prisma.patient.count() }, admissions: { active: await prisma.admission.count({ where: { status: "ACTIVE" } }) }, emergency: { activePatients: 0 }, lab: { pendingReports: 0 } }));
app.get("/api/v1/patients", async (request) => { const q = (request.query as { search?: string }).search?.trim(); const data = await prisma.patient.findMany({ where: q ? { OR: [{ mrn: { contains: q, mode: "insensitive" } }, { firstName: { contains: q, mode: "insensitive" } }, { lastName: { contains: q, mode: "insensitive" } }, { phone: { contains: q } }] } : undefined, include: { admissions: { where: { status: "ACTIVE" }, include: { bed: { include: { ward: true, room: true } } }, take: 1 } }, orderBy: { createdAt: "desc" }, take: 100 }); return { data }; });
app.post("/api/v1/patients", async (request, reply) => { const body = request.body as { firstName?: string; lastName?: string; dateOfBirth?: string; phone?: string; email?: string; hospitalId?: string }; if (!required(body.firstName) || !required(body.lastName)) return reply.code(400).send({ error: "firstName and lastName are required" }); const patient = await prisma.patient.create({ data: { mrn: mrn(), firstName: body.firstName!.trim(), lastName: body.lastName!.trim(), dateOfBirth: body.dateOfBirth ? new Date(body.dateOfBirth) : undefined, phone: body.phone?.trim() || undefined, email: body.email?.trim() || undefined, hospitalId: await hospitalIdFor(body.hospitalId) } }); return reply.code(201).send(patient); });
app.get("/api/v1/patients/:id", async (request, reply) => { const { id } = request.params as { id: string }; const patient = await prisma.patient.findUnique({ where: { id }, include: { allergies: true, admissions: { include: { bed: { include: { ward: true, room: true } } }, orderBy: { admittedAt: "desc" } }, vitals: { orderBy: { recordedAt: "desc" }, take: 20 }, appointments: { orderBy: { scheduledAt: "desc" }, take: 20 } } }); if (!patient) return reply.code(404).send({ error: "Patient not found" }); return patient; });
app.get("/api/v1/beds", async (request) => { const query = request.query as { status?: string; wardId?: string; search?: string }; const data = await prisma.bed.findMany({ where: { ...(query.status ? { status: query.status as any } : {}), ...(query.wardId ? { wardId: query.wardId } : {}), ...(query.search ? { OR: [{ number: { contains: query.search, mode: "insensitive" } }, { room: { number: { contains: query.search, mode: "insensitive" } } }] } : {}) }, include: { ward: { include: { floor: { include: { building: { include: { campus: true } } } } } }, room: true }, orderBy: [{ wardId: "asc" }, { number: "asc" }] }); return { data, counts: { total: await prisma.bed.count(), available: await prisma.bed.count({ where: { status: "AVAILABLE" } }), occupied: await prisma.bed.count({ where: { status: "OCCUPIED" } }), cleaning: await prisma.bed.count({ where: { status: "CLEANING" } }), reserved: await prisma.bed.count({ where: { status: "RESERVED" } }) } }; });
app.post("/api/v1/admissions", async (request, reply) => { const body = request.body as { patientId?: string; bedId?: string }; if (!body.patientId || !body.bedId) return reply.code(400).send({ error: "patientId and bedId are required" }); try { return reply.code(201).send(await prisma.$transaction(async tx => { const bed = await tx.bed.findUnique({ where: { id: body.bedId } }); const active = await tx.admission.findFirst({ where: { patientId: body.patientId, status: "ACTIVE" } }); if (!bed || bed.status !== "AVAILABLE") throw new Error("BED"); if (active) throw new Error("ACTIVE"); const admission = await tx.admission.create({ data: { patientId: body.patientId!, bedId: body.bedId! } }); await tx.bed.update({ where: { id: body.bedId! }, data: { status: "OCCUPIED" } }); return admission; })); } catch (e) { return reply.code(409).send({ error: e instanceof Error && e.message === "ACTIVE" ? "Patient already has an active admission" : "Bed is not available" }); } });
app.post("/api/v1/admissions/:id/transfer", async (request, reply) => { const { id } = request.params as { id: string }; const { toBedId } = request.body as { toBedId?: string }; if (!toBedId) return reply.code(400).send({ error: "toBedId is required" }); try { return await prisma.$transaction(async tx => { const admission = await tx.admission.findUnique({ where: { id } }); const target = await tx.bed.findUnique({ where: { id: toBedId } }); if (!admission || admission.status !== "ACTIVE" || !target || target.status !== "AVAILABLE") throw new Error(); await tx.admissionTransfer.create({ data: { admissionId: id, fromBedId: admission.bedId, toBedId } }); await tx.bed.update({ where: { id: admission.bedId }, data: { status: "AVAILABLE" } }); await tx.bed.update({ where: { id: toBedId }, data: { status: "OCCUPIED" } }); return tx.admission.update({ where: { id }, data: { bedId: toBedId } }); }); } catch { return reply.code(409).send({ error: "Transfer could not be completed" }); } });
app.post("/api/v1/admissions/:id/discharge", async (request, reply) => { const { id } = request.params as { id: string }; try { return await prisma.$transaction(async tx => { const admission = await tx.admission.findUnique({ where: { id } }); if (!admission || admission.status !== "ACTIVE") throw new Error(); await tx.bed.update({ where: { id: admission.bedId }, data: { status: "CLEANING" } }); return tx.admission.update({ where: { id }, data: { status: "DISCHARGED", dischargedAt: new Date() } }); }); } catch { return reply.code(404).send({ error: "Active admission not found" }); } });
app.addHook("onClose", async () => prisma.$disconnect());
await app.listen({ host: "0.0.0.0", port: Number(process.env.PORT || 4000) });
