"use client";
import {useEffect,useMemo,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"";
type Event={id:string;createdAt:string;action:string;entity:string;entityId?:string;user?:{email?:string;name?:string;roles?:string[]};status?:string;requestId?:string;method?:string;path?:string;module?:string;reason?:string;before?:unknown;after?:unknown};
export default function Audit(){
 const[data,setData]=useState<Event[]>([]),[error,setError]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState("ALL"),[module,setModule]=useState("ALL"),[selected,setSelected]=useState<Event|null>(null),[live,setLive]=useState(true);
 async function load(){try{const r=await fetch(API+"/api/v1/audit?limit=1000",{cache:"no-store"});if(!r.ok)throw new Error("Audit API unavailable");setData((await r.json()).data||[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load audit trail")}}
 useEffect(()=>{load();const t=setInterval(()=>{if(live)load()},5000);return()=>clearInterval(t)},[live]);
 const modules=useMemo(()=>Array.from(new Set(data.map(x=>x.module||x.entity).filter(Boolean))).sort(),[data]);
 const filtered=useMemo(()=>data.filter(x=>(status==="ALL"||x.status===status)&&(module==="ALL"||(x.module||x.entity)===module)&&(!search||JSON.stringify(x).toLowerCase().includes(search.toLowerCase()))),[data,status,module,search]);
 return <main className="page"><header><div><small>GOVERNANCE / TRACEABILITY</small><h1>Audit Trail</h1><p>Every operational request and change is recorded with actor, status, request ID and details.</p></div><div className="headActions"><span className={live?"live":"paused"}>● {live?"Live":"Paused"}</span><button onClick={()=>setLive(v=>!v)}>{live?"Pause live":"Resume live"}</button><button onClick={load}>↻ Refresh</button></div></header>
 {error&&<div className="error">{error}</div>}
 <section className="stats"><article><b>{data.length}</b><span>Total events</span></article><article><b>{data.filter(x=>x.status==="SUCCESS").length}</b><span>Successful</span></article><article><b>{data.filter(x=>x.status==="FAILED").length}</b><span>Failed</span></article><article><b>{new Set(data.map(x=>x.entityId).filter(Boolean)).size}</b><span>Entities affected</span></article></section>
 <section className="panel"><div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search patient, MRN, operation, request ID…"/><select value={module} onChange={e=>setModule(e.target.value)}><option>ALL</option>{modules.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>ALL</option><option>SUCCESS</option><option>FAILED</option></select></div>
 <div className="tableWrap"><table><thead><tr><th>Time</th><th>Status</th><th>Action</th><th>Module</th><th>Entity / ID</th><th>User</th><th>Request ID</th><th>Method</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id} onClick={()=>setSelected(x)}><td>{new Date(x.createdAt).toLocaleString()}</td><td><span className={x.status==="SUCCESS"?"ok":"bad"}>{x.status||"INFO"}</span></td><td><b>{x.action}</b></td><td>{x.module||x.entity}</td><td>{x.entity}{x.entityId?" · "+x.entityId:""}</td><td>{x.user?.name||x.user?.email||"System"}</td><td>{x.requestId||"—"}</td><td>{x.method||"—"}</td></tr>)}{!filtered.length&&<tr><td colSpan={8} className="empty">No audit events match the selected filters.</td></tr>}</tbody></table></div></section>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><small>OPERATION DETAIL</small><h2>{selected.action}</h2><div className="detailGrid"><div><label>Status</label><b>{selected.status}</b></div><div><label>Module</label><b>{selected.module||selected.entity}</b></div><div><label>User</label><b>{selected.user?.name||selected.user?.email||"System"}</b></div><div><label>Request ID</label><b>{selected.requestId||"—"}</b></div><div><label>Entity</label><b>{selected.entity}</b></div><div><label>Entity ID</label><b>{selected.entityId||"—"}</b></div><div><label>Method</label><b>{selected.method||"—"}</b></div><div><label>Path</label><b>{selected.path||"—"}</b></div></div>{selected.reason&&<div className="reason">{selected.reason}</div>}<h3>Before</h3><pre>{JSON.stringify(selected.before??null,null,2)}</pre><h3>After / Request</h3><pre>{JSON.stringify(selected.after??null,null,2)}</pre></div></div>}
 <style jsx>{\`*{box-sizing:border-box}.page{min-height:100vh;background:#f4f7fb;color:#172033;padding:38px;font-family:Inter,system-ui,sans-serif}header{max-width:1400px;margin:auto;display:flex;justify-content:space-between;align-items:center;gap:20px}small{font-size:10px;letter-spacing:1px;color:#7c899b;font-weight:800}h1{margin:5px 0;font-size:30px}p{color:#8490a0;font-size:12px}.headActions{display:flex;align-items:center;gap:8px}.headActions button{border:0;background:#172b42;color:white;border-radius:9px;padding:10px 13px;cursor:pointer;font-size:11px}.live,.paused{font-size:10px;font-weight:800}.live{color:#168a67}.paused{color:#8b95a4}.stats{max-width:1400px;margin:24px auto 14px;display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stats article{background:#fff;border:1px solid #e2e8ef;border-radius:12px;padding:15px}.stats b{display:block;font-size:23px}.stats span{font-size:10px;color:#8793a4}.panel{max-width:1400px;margin:auto;background:white;border:1px solid #e2e8ef;border-radius:16px;overflow:hidden}.filters{display:flex;gap:9px;padding:15px;border-bottom:1px solid #e8edf2}.filters input,.filters select{border:1px solid #dfe5ec;border-radius:8px;padding:10px;font-size:11px;background:#fff}.filters input{flex:1}.tableWrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:11px;min-width:1050px}th,td{text-align:left;padding:12px 13px;border-bottom:1px solid #edf0f4;white-space:nowrap}th{font-size:9px;letter-spacing:1px;color:#7d8999;text-transform:uppercase}td{color:#5d6b7d;cursor:pointer}.ok,.bad{display:inline-block;border-radius:999px;padding:4px 7px;font-size:8px;font-weight:800}.ok{background:#e8f7f1;color:#16845f}.bad{background:#fff0f0;color:#b04450}.empty{text-align:center;padding:35px;color:#909baa}.error{max-width:1400px;margin:20px auto;background:#fff0f0;padding:12px;border-radius:10px;color:#a33}.overlay{position:fixed;inset:0;background:#08132266;z-index:20}.drawer{position:absolute;right:0;top:0;height:100%;width:min(620px,100%);background:#fff;padding:30px;overflow:auto;box-shadow:-15px 0 40px #0002}.close{position:absolute;right:18px;top:18px;border:0;border-radius:50%;width:30px;height:30px;background:#f1f4f7;cursor:pointer;font-size:20px}h2{margin:6px 0 22px;font-size:22px}h3{font-size:11px;margin:20px 0 7px}.detailGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.detailGrid div{background:#f7f9fb;border-radius:8px;padding:10px}.detailGrid label,.detailGrid b{display:block}.detailGrid label{font-size:8px;color:#8b97a8;margin-bottom:4px}.detailGrid b{font-size:10px;word-break:break-word}.reason{margin-top:12px;background:#fff1f1;color:#a43e48;border-radius:8px;padding:10px;font-size:10px}pre{background:#101a2b;color:#dce6f2;padding:13px;border-radius:9px;font-size:9px;overflow:auto;max-height:220px}@media(max-width:800px){.page{padding:20px}header{align-items:flex-start;flex-direction:column}.stats{grid-template-columns:1fr 1fr}.filters{flex-direction:column}}\`}</style></main>
}