"use client";
import { useEffect, useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000";
type Item={id:string;sku:string;name:string;category?:string;unit:string;quantity:number;reorderLevel:number};
export default function Inventory(){const [items,setItems]=useState<Item[]>([]),[sku,setSku]=useState(""),[name,setName]=useState(""),[qty,setQty]=useState("0"),[reorder,setReorder]=useState("5"),[message,setMessage]=useState("");
const load=async()=>{const r=await fetch(`${API}/api/v1/inventory/items`);const x=await r.json();setItems(x.data||[])};useEffect(()=>{void load()},[]);
async function add(){const r=await fetch(`${API}/api/v1/inventory/items`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sku,name,quantity:Number(qty),reorderLevel:Number(reorder)})});const x=await r.json();setMessage(r.ok?"Stock item created":x.error||"Could not create item");if(r.ok){setSku("");setName("");setQty("0");void load()}}
async function move(i:Item,type:"RECEIPT"|"ISSUE"){const raw=prompt(`${type === "RECEIPT"?"Receive":"Issue"} quantity for ${i.name}`);const n=Number(raw);if(!Number.isInteger(n)||n<1)return;const r=await fetch(`${API}/api/v1/inventory/items/${i.id}/movements`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,quantity:n,reason:type=== "RECEIPT"?"Stock receipt":"Stock issue"})});const x=await r.json();setMessage(r.ok?`${type} recorded`:x.error||"Movement failed");if(r.ok)void load()}
return <main><style>{`*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui;background:#f6f8fb;color:#172033}main{min-height:100vh;padding:32px;max-width:1400px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center}.back{color:#4967d8;text-decoration:none}.grid{display:grid;grid-template-columns:350px 1fr;gap:20px;margin-top:24px}.card{background:#fff;border:1px solid #e5e9f0;border-radius:18px;padding:20px;box-shadow:0 8px 28px #1720330d}input,button{width:100%;padding:12px;border-radius:10px;border:1px solid #d9deea;margin:6px 0 12px;font:inherit}button{background:#172033;color:#fff;cursor:pointer}.item{padding:16px 0;border-bottom:1px solid #edf0f5;display:flex;justify-content:space-between;gap:15px}.muted{color:#6c7585;font-size:13px}.low{color:#b45309;font-weight:700}.actions{display:flex;gap:8px}.actions button{width:auto;padding:8px 10px}@media(max-width:800px){.grid{grid-template-columns:1fr}main{padding:18px}}`}</style><div className="top"><div><a className="back" href="/">← Command Center</a><h1>Inventory & Stock</h1><p className="muted">Hospital supplies, stock receipts and controlled issues.</p></div></div><div className="grid"><section className="card"><h2>Add item</h2><input placeholder="SKU" value={sku} onChange={e=>setSku(e.target.value)}/><input placeholder="Item name" value={name} onChange={e=>setName(e.target.value)}/><input type="number" min="0" placeholder="Opening quantity" value={qty} onChange={e=>setQty(e.target.value)}/><input type="number" min="0" placeholder="Reorder level" value={reorder} onChange={e=>setReorder(e.target.value)}/><button onClick={()=>void add()}>Add inventory item</button>{message&&<p className="muted">{message}</p>}</section><section className="card"><h2>Stock ledger</h2>{!items.length?<p className="muted">No inventory items yet.</p>:items.map(i=><div className="item" key={i.id}><div><b>{i.name}</b><div className="muted">{i.sku} · {i.unit}</div></div><div style={{textAlign:"right"}}><b className={i.quantity<=i.reorderLevel?"low":""}>{i.quantity}</b><div className="muted">reorder at {i.reorderLevel}</div><div className="actions"><button onClick={()=>void move(i,"RECEIPT")}>Receive</button><button onClick={()=>void move(i,"ISSUE")}>Issue</button></div></div></div>)}</section></div></main>}
